export const sliderItems = [
  {
    id: 1,
    img: "https://images.unsplash.com/photo-1504198458649-3128b932f49e?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=687&q=80",
    title: "Spring SALE",
    desc: "Best Collection Hurry Up and Buy",
    bg: "EAEFF2",
    category: "spring",
  },
  {
    id: 2,
    img: "https://images.unsplash.com/photo-1609709295948-17d77cb2a69b?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1976&q=80",
    title: "Summer COLLECTION",
    desc: "Best Collection Hurry Up and Buy    ",
    bg: "EAEFF2",
    category: "summer",
  },
  {
    id: 3,
    img: "https://images.unsplash.com/photo-1453486030486-0a5ffcd82cd9?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=663&q=80",
    title: "Winter Collection",
    desc: "Best Collection Hurry Up and Buy",
    bg: "EAEFF2",
    category: "winter",
  },
  {
    id: 4,
    img: "https://images.unsplash.com/photo-1509319117193-57bab727e09d?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1974&q=80",
    title: "Autumn Collection",
    desc: "Best Collection Hurry Up and Buy",
    bg: "EAEFF2",
    category: "autumn",
  },
];

export const categories = [
  {
    id: 1,
    img: "https://images.unsplash.com/photo-1523359346063-d879354c0ea5?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=687&q=80",
    title: "Women Category!",
    type: "women",
  },
  {
    id: 2,
    img: "https://images.unsplash.com/photo-1622519407650-3df9883f76a5?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=764&q=80",
    title: "Men Category",
    type: "men",
  },
  {
    id: 3,
    img: "https://images.unsplash.com/photo-1460353581641-37baddab0fa2?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1471&q=80",
    title: "Shoes Category!",
    type: "shoes",
  },
];

export const popularProducts = [
  {
    id: 1,
    img: "https://d3o2e4jr3mxnm3.cloudfront.net/Mens-Jake-Guitar-Vintage-Crusher-Tee_68382_1_lg.png",
    title: "T-shirt",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Aut dolores fuga ab ratione exercitationem id voluptas! Impedit atque veritatis sunt, necessitatibus neque numquam reprehenderit ex in dolor. Officiis, quisquam eaque.",
    price: 20,
    colors: ["red", "green"],
    sizes: ["xl", "md", "xxl"],
  },
  {
    id: 2,
    img: "https://d3o2e4jr3mxnm3.cloudfront.net/Mens-Jake-Guitar-Vintage-Crusher-Tee_68382_1_lg.png",
    title: "T-shirt",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Aut dolores fuga ab ratione exercitationem id voluptas! Impedit atque veritatis sunt, necessitatibus neque numquam reprehenderit ex in dolor. Officiis, quisquam eaque.",
    price: 40,
    colors: ["blue"],
    sizes: ["xl", "lg"],
  },
  {
    id: 3,
    img: "https://www.prada.com/content/dam/pradanux_products/U/UCS/UCS319/1YOTF010O/UCS319_1YOT_F010O_S_182_SLF.png",
    title: "T-shirt",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Aut dolores fuga ab ratione exercitationem id voluptas! Impedit atque veritatis sunt, necessitatibus neque numquam reprehenderit ex in dolor. Officiis, quisquam eaque.",
    price: 93,
    colors: ["green"],
    sizes: ["lg", "md"],
  },
  {
    id: 4,
    img: "https://www.burdastyle.com/pub/media/catalog/product/cache/7bd3727382ce0a860b68816435d76e26/107/BUS-PAT-BURTE-1320516/1170x1470_BS_2016_05_132_front.png",
    title: "jeans",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Aut dolores fuga ab ratione exercitationem id voluptas! Impedit atque veritatis sunt, necessitatibus neque numquam reprehenderit ex in dolor. Officiis, quisquam eaque.",
    price: 220,
    colors: ["yellow"],
    sizes: ["xl"],
  },
  {
    id: 5,
    img: "https://images.ctfassets.net/5gvckmvm9289/3BlDoZxSSjqAvv1jBJP7TH/65f9a95484117730ace42abf64e89572/Noissue-x-Creatsy-Tote-Bag-Mockup-Bundle-_4_-2.png",
    title: "coat",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Aut dolores fuga ab ratione exercitationem id voluptas! Impedit atque veritatis sunt, necessitatibus neque numquam reprehenderit ex in dolor. Officiis, quisquam eaque.",
    price: 250,
    colors: ["red"],
    sizes: ["md", "sm"],
  },
  {
    id: 6,
    img: "https://d3o2e4jr3mxnm3.cloudfront.net/Rocket-Vintage-Chill-Cap_66374_1_lg.png",
    title: "shoes",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Aut dolores fuga ab ratione exercitationem id voluptas! Impedit atque veritatis sunt, necessitatibus neque numquam reprehenderit ex in dolor. Officiis, quisquam eaque.",
    price: 199,
    colors: ["green"],
    sizes: ["xl", "md", "xxl"],
  },
  {
    id: 7,
    img: "https://d3o2e4jr3mxnm3.cloudfront.net/Rocket-Vintage-Chill-Cap_66374_1_lg.png",
    title: "hat",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Aut dolores fuga ab ratione exercitationem id voluptas! Impedit atque veritatis sunt, necessitatibus neque numquam reprehenderit ex in dolor. Officiis, quisquam eaque.",
    price: 290,
    colors: ["black"],
    sizes: ["xl", "xxl"],
  },
  {
    id: 8,
    img: "https://www.pngarts.com/files/3/Women-Jacket-PNG-High-Quality-Image.png",
    title: "glasses",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Aut dolores fuga ab ratione exercitationem id voluptas! Impedit atque veritatis sunt, necessitatibus neque numquam reprehenderit ex in dolor. Officiis, quisquam eaque.",
    price: 33,
    colors: ["red"],
    sizes: ["xl", "md"],
  },
];
